### ISSUE TITLE
Gestaltung der GUI für die frontalunterricht-basics.

### ISSUE THREAD

**Issue by kirschmarsch** [holtwick/peer2school#46]
Als Schüler möchte ich alle für mich wichtigen Elemente übersichtlich dargestellt bekommen: 
- [x] das Whiteboard (#7 )
- [x] das Video des Lehrers (#28 und #20 )
- [x] mein eigenes Bild
- [ ] eventuell das Bild eines aufgerufenen Schülers (Kommunikation mit den Assignees von #19 )
- [ ] eine Namensliste aller Teilnehmer (#30 )
- [x] den Chat.
Als Lehrer möchte ich alle für mich wichtigen Elemente übersichtlich dargestellt bekommen:

Probleme momentan sind: 
- [x] Bei vielen Teilnehmern wird der Chat "aus dem Bild gedrängt". 
- [x] Der Pull-Request zur Anzeige der Videos #35 ist wegen Merge-Konflikten nicht abgeschlossen.

**Comment by gruenerf** [comment]
Hier

**Comment by klaraschlueter** [comment]
@gruenerf , möchtest Du hier auf einer jetzt stabilen Version nochmal weiterarbeiten, oder sollen wir den Issue schließen?

**Comment by holtwick** [comment]
Broke down the last open issues into #62
